title: Mootable 3D Print
description: 3D print resources by mootable
theme: just-the-docs

url: https://mootable.github.io/3dprint/

aux_links:
  Template Repository: https://github.com/mootable/3dprint
