title: Mootable 3D Print
description: 3D print resources by mootable
theme: just-the-docs
repository: mootable/3dprint # for github-metadata

permalink: pretty

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: https://mootable.github.io/3dprint/

aux_links:
  Github Repository: https://github.com/mootable/3dprint
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.0.2"
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/mootable logo.svg"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"